remote-theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
  
title: Quantum Chess Documentation
description: Official documentation for the Quantum Chess engine.
color_scheme: dark

ga_tracking: G-7T33Q4PTSW
ga_tracking_anonymize_ip: true

defaults::
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
