theme: jekyll-theme-slate
title: Quantum Chess Documentation
description: Official documentation for the Quantum Chess engine.
github:
  is_project_page: false

defaults:
  #_docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
